INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (1, 'Ash', 'Ketchum', 'Pallet Town', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (2, 'Misty', 'Williams', 'Cerulean City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (3, 'Brock', 'Harrison', 'Pewter City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (4, 'Gary', 'Oak', 'Pallet Town', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (5, 'Professor', 'Oak', 'Pallet Town Lab', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (6, 'Lt.', 'Surge', 'Vermilion City Gym', 2);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (7, 'Erika', 'Celadon', 'Celadon City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (8, 'Sabrina', 'Natsume', 'Saffron City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (9, 'Koga', 'Fuchsia', 'Fuchsia City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (10, 'Blaine', 'Cinnabar', 'Cinnabar Island Gym', 2);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (11, 'Giovanni', 'Rocket', 'Viridian City Gym', 6);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (12, 'Lance', 'Dragon', 'Indigo Plateau', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (13, 'Lorelei', 'Prima', 'Elite Four', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (14, 'Bruno', 'Shiba', 'Elite Four', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (15, 'Agatha', 'Kikuko', 'Elite Four', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (16, 'Falkner', 'Violet', 'Violet City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (17, 'Bugsy', 'Azalea', 'Azalea Town Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (18, 'Whitney', 'Goldenrod', 'Goldenrod City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (19, 'Morty', 'Ecruteak', 'Ecruteak City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (20, 'Chuck', 'Cianwood', 'Cianwood City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (21, 'Jasmine', 'Olivine', 'Olivine City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (22, 'Pryce', 'Mahogany', 'Mahogany Town Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (23, 'Clair', 'Blackthorn', 'Blackthorn City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (24, 'Will', 'Elite', 'Elite Four Johto', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (25, 'Karen', 'Dark', 'Elite Four Johto', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (26, 'May', 'Maple', 'Littleroot Town', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (27, 'Dawn', 'Berlitz', 'Twinleaf Town', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (28, 'Serena', 'Yvonne', 'Vaniville Town', 4);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (29, 'Clemont', 'Lumiose', 'Lumiose City Gym', 4);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (30, 'Cynthia', 'Shirona', 'Sinnoh Champion', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (31, 'Steven', 'Stone', 'Hoenn Champion', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (32, 'Wallace', 'Sootopolis', 'Sootopolis City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (33, 'Roxanne', 'Rustboro', 'Rustboro City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (34, 'Brawly', 'Dewford', 'Dewford Town Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (35, 'Wattson', 'Mauville', 'Mauville City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (36, 'Flannery', 'Lavaridge', 'Lavaridge Town Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (37, 'Norman', 'Petalburg', 'Petalburg City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (38, 'Winona', 'Fortree', 'Fortree City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (39, 'Tate', 'Mossdeep', 'Mossdeep City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (40, 'Liza', 'Mossdeep', 'Mossdeep City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (41, 'Juan', 'Sootopolis', 'Sootopolis City Gym', 7);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (42, 'Roark', 'Oreburgh', 'Oreburgh City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (43, 'Gardenia', 'Eterna', 'Eterna City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (44, 'Maylene', 'Veilstone', 'Veilstone City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (45, 'Crasher', 'Wake', 'Pastoria City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (46, 'Fantina', 'Hearthome', 'Hearthome City Gym', 4);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (47, 'Byron', 'Canalave', 'Canalave City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (48, 'Candice', 'Snowpoint', 'Snowpoint City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (49, 'Volkner', 'Sunyshore', 'Sunyshore City Gym', 1);
INSERT INTO owner (Id, FirstName, LastName, Gym, CountryId) VALUES (50, 'Paul', 'Veilstone', 'Trainer', 1);
