INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (1, 'Best Starter Ever!', 'Bulbasaur is an excellent starter Pokemon with great type coverage and balanced stats.', 5, 1, 1);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (2, 'Powerful Evolution', 'Charizard's flying ability combined with fire attacks makes it incredibly versatile in battles.', 5, 1, 6);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (3, 'Defensive Powerhouse', 'Blastoise's water cannons are devastating and its shell provides amazing defense.', 5, 2, 9);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (4, 'Electric Companion', 'Pikachu refuses to evolve but remains incredibly powerful and loyal.', 5, 1, 25);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (5, 'Psychic Master', 'Alakazam's psychic abilities are unmatched. Incredible intelligence and speed.', 5, 4, 65);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (6, 'Dragon Champion', 'Dragonite is gentle despite its power. A true champion's Pokemon.', 5, 6, 149);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (7, 'Legendary Power', 'Mewtwo's power is almost too much to handle. Requires experienced training.', 5, 4, 150);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (8, 'Mysterious Pokemon', 'Mew is adorable yet powerful. Perfect stats across the board!', 5, 4, 151);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (9, 'Fire Starter', 'Cyndaquil is a reliable fire-type starter with great potential.', 4, 1, 155);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (10, 'Water Power', 'Feraligatr's jaw strength is incredible. Highly recommend!', 5, 2, 160);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (11, 'Cute but Powerful', 'Pichu is adorable but needs careful training to avoid self-damage.', 4, 9, 172);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (12, 'Happiness Pokemon', 'Togepi brings joy wherever it goes. Great for new trainers.', 5, 10, 175);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (13, 'Electric Sheep', 'Ampharos is a fantastic electric type with great special attack.', 5, 12, 181);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (14, 'Sun Pokemon', 'Espeon's psychic abilities developed from strong friendship.', 5, 9, 196);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (15, 'Moonlight Pokemon', 'Umbreon's dark typing and defense make it perfect for night battles.', 5, 13, 197);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (16, 'Legendary Diving', 'Lugia's power over the sea is magnificent. Truly legendary!', 5, 6, 249);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (17, 'Rainbow Pokemon', 'Ho-Oh is majestic and its sacred fire is incredibly powerful.', 5, 6, 250);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (18, 'Time Traveler', 'Celebi can travel through time! An amazing grass/psychic type.', 5, 4, 251);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (19, 'Rock Solid', 'Geodude is tough and perfect for beginner trainers.', 4, 3, 74);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (20, 'Water Ninja', 'Greninja is fast and powerful with excellent water/dark typing.', 5, 11, 658);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (21, 'Fighting Spirit', 'Machamp's four arms deliver devastating punches!', 5, 14, 68);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (22, 'Ghost Master', 'Gengar is my favorite ghost type. Perfect for strategic battles.', 5, 7, 94);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (23, 'Ice Queen', 'Lapras is gentle and powerful. Great for water transportation.', 5, 2, 131);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (24, 'Sleeping Giant', 'Snorlax is incredibly bulky and surprisingly fast when awake.', 4, 1, 143);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (25, 'Bug Champion', 'Scyther's speed and slashing attacks are phenomenal.', 5, 17, 123);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (26, 'Steel Defense', 'Steelix has incredible defense. Nearly impenetrable!', 5, 3, 208);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (27, 'Dragon Ruler', 'Garchomp is the perfect combination of power and speed.', 5, 7, 445);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (28, 'Aura Pokemon', 'Lucario's aura abilities make it unique and powerful.', 5, 8, 448);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (29, 'Flame Body', 'Magmar's flame body ability is great for hatching eggs.', 4, 24, 126);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (30, 'Forest Guardian', 'Celebi protected our forest. An amazing experience!', 5, 23, 251);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (31, 'Water Starter', 'Squirtle Squad member here! Best water starter hands down.', 5, 1, 7);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (32, 'Evolution Master', 'Eevee's evolution options make it incredibly versatile.', 5, 4, 133);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (33, 'Poison Expert', 'Nidoking has amazing type coverage with poison and ground.', 4, 9, 34);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (34, 'Flying High', 'Pidgeot is one of the fastest flying types in Kanto.', 4, 1, 18);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (35, 'Underground Mole', 'Dugtrio's ground attacks are super effective!', 4, 3, 51);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (36, 'Grass Specialist', 'Vileplume has powerful grass moves and sleep powder.', 4, 7, 45);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (37, 'Water Psychic', 'Starmie's dual typing makes it unpredictable in battles.', 5, 2, 121);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (38, 'Fighting Champ', 'Hitmonlee's kicks are legendary!', 5, 14, 106);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (39, 'Rare Pokemon', 'Chansey is great for healing team members.', 5, 29, 113);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (40, 'Legendary Bird', 'Articuno's ice beam is incredibly powerful!', 5, 6, 144);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (41, 'Thunder Bird', 'Zapdos controls electricity like no other Pokemon.', 5, 6, 145);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (42, 'Fire Bird', 'Moltres is majestic and its fire attacks are devastating.', 5, 6, 146);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (43, 'Dragon Type', 'Dratini is cute but will evolve into a powerful dragon.', 4, 12, 147);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (44, 'Grass Type', 'Chikorita is an underrated grass starter.', 4, 9, 152);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (45, 'Fire Mouse', 'Typhlosion's eruption attack is incredible!', 5, 1, 157);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (46, 'Bug Type', 'Heracross is the strongest bug Pokemon I've trained.', 5, 17, 214);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (47, 'Steel Type', 'Scizor's metal coating makes it nearly invincible.', 5, 8, 212);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (48, 'Water Dragon', 'Kingdra is an excellent water/dragon combination.', 5, 2, 230);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (49, 'Rock Type', 'Tyranitar is a pseudo-legendary with amazing stats.', 5, 7, 248);
INSERT INTO review (Id, Title, Text, Rating, ReviewerId, PokemonId) VALUES (50, 'Normal Type', 'Persian is fast and elegant. Great for speed battles.', 4, 1, 53);
